per_listener_settings true

listener 8883 0.0.0.0
allow_anonymous false
password_file /tmp/mosquitto-passwords
cafile /mosquitto/data/tls/ca.crt
certfile /mosquitto/data/tls/server.crt
keyfile /mosquitto/data/tls/server.key
require_certificate false

persistence true
persistence_location /mosquitto/data/

log_dest stdout
connection_messages true
